# Generated by Django 4.1.1 on 2022-10-15 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_authors',
            field=models.ManyToManyField(related_name='bookmark_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
