# Generated by Django 4.1.1 on 2022-10-16 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_post_bookmark_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_authros_comments',
            field=models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
